stages:
  - build
  - test

Build-Verademo: &validate
  stage: build
  image: maven:latest
  artifacts:
    paths:
      - target/
  script:
    #- cd verademo
    #- mvn package
    - mvn clean package
  # Cache downloaded dependencies and plugins between builds.
  # To keep cache across branches add 'key: "$CI_JOB_NAME"'
  cache:
    paths:
      - .m2/repository
      - target/

variables:
  MAVEN_OPTS: "-Djava.awt.headless=true -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
#
#pipeline scan:
#  stage: test
#  image: ctcampbelldocker/veracode-ci-examples
#  dependencies:
#    - Build-Verademo
#  artifacts:
#    name: ${CI_PROJECT_NAME}_${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHA}_pipeline-results
#    paths:
#      - results.json
#    expire_in: 1 week
#    when: always
#  script:
#    - curl -O https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip
#    - unzip pipeline-scan-LATEST.zip pipeline-scan.jar
#    - java -jar pipeline-scan.jar
#      --veracode_api_id "${VERACODE_CI_API_ID}"
#      --veracode_api_key "${VERACODE_CI_API_KEY}"
#      --file "target/verademo.war"

#      --project_name "${CI_PROJECT_PATH}"
#      --project_url "${CI_REPOSITORY_URL}"
#      --project_ref "${CI_COMMIT_REF_NAME}"
#      --fail_on_severity="Very High, High"
#      --fail_on_cwe="80"
#      --baseline_file "${CI_BASELINE_PATH}"

#veracode_sca_job:
#  stage: test
#  image: ctcampbelldocker/veracode-ci-examples
#  script:
#    - curl -sSL https://download.sourceclear.com/ci.sh | sh
#
Veracode-policy-scan:
  stage: test
  image: ctcampbelldocker/veracode-ci-examples
  script:
    - echo ${VERACODE_API_ID}
    - echo ${VERACODE_API_KEY}
    - java -jar /veracode/veracode-wrapper.jar -vid ${VERACODE_CI_API_ID} -vkey ${VERACODE_CI_API_KEY}
      -action UploadAndScan -appname Verademo -autoscan true -createprofile true
      -filepath target/verademo.war -version "job ${CI_JOB_ID} in pipeline ${CI_PIPELINE_ID}"
      -scantimeout 120

#greenlight_job:
#  stage: test
#  image: ctcampbelldocker/veracode-ci-examples
#  dependencies:
#    - Build-Verademo
#  artifacts:
#    name: ${CI_PROJECT_NAME}_${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHA}_greenlight-results
#    paths:
#      - results.json
#    expire_in: 1 week
#    when: always
#  script:
#    - echo ${VERACODE_CI_API_ID}
#    - echo ${VERACODE_CI_API_KEY}
#    - curl -O https://downloads.veracode.com/securityscan/gl-scanner-java-LATEST.zip
#    - unzip gl-scanner-java-LATEST.zip gl-scanner-java.jar
#    - java -jar gl-scanner-java.jar
#      --api_id ${VERACODE_CI_API_ID}
#      --api_secret_key ${VERACODE_CI_API_KEY}
#      --source_dir "src/main/java"
#      --build_dir "target/classes"
#      --project_name "${CI_PROJECT_NAME}"
#      --project_url "${CI_PROJECT_URL}"
#      --project_ref "${CI_COMMIT_REF_NAME}"
#      --previous_job_name "${CI_JOB_NAME}"
#      --gitlab_api_token "${GITLAB_TOKEN}"

# "${CI_PROJECT_NAME}"
#    - curl -o api.zip https://search.maven.org/remotecontent?filepath=com/veracode/vosp/api/wrappers/vosp-api-wrappers-java/19.3.5.7/vosp-api-wrappers-java-19.3.5.7-dist.zip
#    - apt install unzip
#    - unzip api.zip
