# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
  Veracode_SAST_Policy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Veracode Upload And Scan
      # You may pin to the exact commit or the version.
      # uses: veracode/veracode-uploadandscan-action@c5e63c8383debb26a0d48250eab75d94327635ba
      uses: veracode/veracode-uploadandscan-action@0.2.1
      env:
        VERACODE_CI_API_ID: ${{ secrets.VERACODE_CI_API_ID }}
      with:
        # appname
        appname: Verademo # default is ${{ github.repository }}
        # createprofile
        createprofile: # default is true
        # filepath
        filepath: target/verademo.war
        # version
        version: 'Github Workflow - ${{ github.run_id }}' # default is Scan from Github job: ${{ github.run_id }}
        # vid
        vid: ${{ env.VERACODE_CI_API_ID }}
        # vkey
        vkey: ${{ secrets.VERACODE_CI_API_KEY }}
        # true or flase
        createsandbox: # optional
        # name of the sandbox
        sandboxname: # optional
        # wait X minutes for the scan to complete
        scantimeout: # optional
        # modules to exclude from module selection
        exclude: # optional
        # modules to include in module selection
        include: # optional
        # business criticality - policy selection
        criticality: # optional
        # filename pattern
        pattern: # optional
        # replacement
        replacement: # optional
        # replacement
        sandboxid: # optional
        # All top level modules
        scanallnonfataltoplevelmodules: # optional
        # platform selected modules
        selected: # optional
        # selected modules like from previous scan
        selectedpreviously: # optional
        # teams
        teams: # optional
        # teams
        toplevel: # optional

